FROM fedora:36 as builder

RUN mkdir /toybox
ADD http://landley.net/toybox/bin/toybox-x86_64 /toybox/toybox
RUN chmod +x /toybox/toybox
WORKDIR /toybox
RUN for i in $(./toybox); do ln -s toybox $i; done
RUN curl -L https://github.com/moparisthebest/static-curl/releases/download/v7.79.1/curl-amd64 > curl
RUN chmod +x ./curl

FROM distroless:base

COPY --from=builder /toybox /bin

ENTRYPOINT [ "sh" ]