FROM fedora:36 as builder

RUN mkdir /toybox
ADD http://landley.net/toybox/bin/toybox-x86_64 /toybox/toybox
RUN chmod +x /toybox/toybox
WORKDIR /toybox
RUN for i in $(./toybox); do ln -s toybox $i; done

FROM distroless:static

COPY --from=builder /toybox /bin

ENTRYPOINT [ "sh" ]