FROM fedora:36 as builder

FROM distroless:static

COPY --from=builder /usr/lib64/libc.so.6 /usr/lib64/libc.so.6
COPY --from=builder /lib64/libc.so.6 /lib64/libc.so.6
COPY --from=builder /lib64/libpthread.so.0 /lib64/libpthread.so.0
