name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        docker build -t distroless:static -f Containerfile.1.static .
        docker build -t distroless:static-debug -f Containerfile.1.static-debug .
        docker build -t distroless:base -f Containerfile.2.base .
        docker build -t distroless:base-debug -f Containerfile.2.base-debug .

    - name: Test
      run: |
        CGO_ENABLED=0 go build check_certs.go
        docker build -t distroless:static-test -f Containerfile.1.static-test .
        docker run distroless:static-test

    - name: Container Structure Test
      run: curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 && chmod +x container-structure-test-linux-amd64 && mkdir -p $HOME/bin && export PATH=$PATH:$HOME/bin && mv container-structure-test-linux-amd64 $HOME/bin/container-structure-test
      run: |
        container-structure-test test --config base.yaml --image distroless:base-debug

    - name: Container Structure Test
      run: curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 && chmod +x container-structure-test-linux-amd64 && mkdir -p $HOME/bin && export PATH=$PATH:$HOME/bin && mv container-structure-test-linux-amd64 $HOME/bin/container-structure-test
      run: |
        container-structure-test test --config static.yaml --image distroless:static-test